name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Stop and remove existing containers (if any)
      - name: Stop existing containers
        run: |
          docker compose -f docker-compose.yml down

      # Build the Docker containers with no cache to ensure latest changes
      - name: Build Docker containers
        run: |
          docker compose -f docker-compose.yml build --no-cache

      # Start up the containers in detached mode
      - name: Deploy updated containers
        run: |
          docker compose -f docker-compose.yml up -d
