name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    # Check if the container exists and stop it
    - name: Stop Docker container if it exists
      run: |
        if [ "$(docker ps -q -f name=ft)" ]; then
          echo "Stopping container ft..."
          docker stop ft
        else
          echo "Container ft does not exist or is not running."
        fi
    
    # Build the Docker image
    - name: Build Docker image
      run: docker build -t ituacm-ft .

    # Run the Docker container
    - name: Run Docker container
      run: docker run -d -p 3000:3000 --name ft ituacm-ft
